### PR TITLE
Create FAQS

### PR DESCRIPTION
**Pull request by olayhemy**
A Frequently Asked Question section (FAQs) is without a doubt the most commonly used tool in self-service. Service users tend to feel that their question is the most important question, and they are right. With Frequently Asked Questions, service users will find answers to possible questions.

### CODE REVIEW

**Review by jahirfiquitiva — CHANGES_REQUESTED** [review]
Thanks for the changes you did. 🙂 Unfortunately, there are still some things to be fix:
1. The FAQs must be developer oriented. Frames is not a real app, but more like a library. That said, final users won't really see the core of Frames.
2. There are some typos in the file, where you used `Frame` instead of `Frames`

As a tip: you don't have to create a whole new fork, or a whole new pull request. Just update what is needed in the already existent fork/branch and this pull request will be updated automatically 😉

**Comment by olayhemy** [comment]
Thanks for the observation, I've fixed the frames typo. Check and merge, Thanks.

**Review by jahirfiquitiva — CHANGES_REQUESTED** [review]
Thanks for the changes!🙂

Once again, the questions must be developer oriented, and please update the README to point to the FAQS

**Comment by olayhemy** [comment]
Thanks for the feedback, I'm not a developer I'm an article writer. I love this project and like to contribute, don't really know anything about app development.

**Comment by olayhemy** [comment]
Thanks, can I  write an About Us or Contact Us for this project?

**Comment by jahirfiquitiva** [comment]
@olayhemy I honestly don't see the need of it. The info is already shared by GitHub and it's also mentioned in README

**Comment by charles935** [comment]
Can u please tell me how will i add adcodes bcz it don't have XML files(layout).....plz help

**Comment by jahirfiquitiva** [comment]
@charles935 This is not the place to ask that. Anyways, it's mentioned in [README](https://github.com/jahirfiquitiva/Frames/#library-source) that further changes/additions to the app, must be done **completely by yourself**. I don't provide support for the given case. Sorry.

**Pull request closed without merging**
